### ISSUE TITLE
tests directory missing, impossible to build

### ISSUE THREAD

**Issue by giraud** [cometkim/rescript-vitest#1]
I installed the bindings with yarn `yarn add -D rescript-vitest` and rescript build always fail with:
```
Dependency on rescript-vitest
Fatal error: exception Unix.Unix_error(20, "stat", "C:\\sources\\......\\node_modules\\rescript-vitest\\tests")
```

And in fact `tests` directory is not present in the downloaded package. If I add `tests` manually , it compiles.
maybe the directory should be included in the distribution package.

**Comment by cometkim** [comment]
Thanks for reporting.

fixed in v0.1.1
