### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by vinibispo** [cometkim/rescript-vitest#11]
# How to run
```sh
git clone https://github.com/vinibispo/minimal-reproducible-example-rescript-vitest-problem
cd minimal-reproducible-example-rescript-vitest-problem
yarn --frozen-lockfile
```
In a terminal use `yarn res:dev`
In another run `yarn vitest`
You will get this message
![image](https://user-images.githubusercontent.com/48097622/236201732-c0bb27da-1b3a-4379-8425-4bedbec75650.png)

**Comment by cometkim** [comment]
This may be a version compatibility issue.

Since the package already has vitest as a dependency, you shouldn't add a new version.

**Comment by cometkim** [comment]
Close this since it duplicates #10
