### ISSUE TITLE
JSX

### ISSUE THREAD

**Issue by vasco3** [cometkim/rescript-vitest#12]
does it support testing React components?

**Comment by cometkim** [comment]
Please describe your issue?

**Comment by vasco3** [comment]
I would like to test modules with React components 
like in this example
https://github.com/vitest-dev/vitest/blob/main/examples/react/test/basic.test.tsx

looks like it requires an extension .jsx but not sure how would this work with vitest and rescript

sounds like it isn't a concern from this lib
