### ISSUE TITLE
Not working with Rescript v11 due to uncurried by default

### ISSUE THREAD

**Issue by mxj4** [cometkim/rescript-vitest#14]
Recently, ReScript v11 beta switched to uncurried by default, and this binding stops working. I tried adding
```
"uncurried": false,
```
in `bsconfig.json`, but the compiler still compiles functions without `@uncurry` annotation to uncurried functions, not sure if this is a rescript compiler issue, or maybe I modified `bsconfig.json` incorrectly, or maybe there is some sort of caching ignoring my modification to `bsconfig.json` deep under `node_modules` folder.

**Comment by cometkim** [comment]
IMO, ReScript should ensure backwards compatibility when `uncurried: false` explicitly. Are there any issues upstream?

**Comment by cometkim** [comment]
[Currying also causes problem with vitest interop](https://github.com/cometkim/rescript-vitest/issues/10#issuecomment-1540439004), I plan to fix it in the next major version.
