### ISSUE TITLE
all tests are skipped

### ISSUE THREAD

**Issue by giraud** [cometkim/rescript-vitest#3]
Hi,
using `rescript-vitest#0.1.1` with `vitest#0.2.7`, all tests written in rescript are skipped, they are never run and never fail.

this is the generated code: 
```
Vitest.describe("T1", undefined, (function (param) {
        return Vitest.it("T11", undefined, (function (_t) {
                      Vitest$1.expect(1).toEqual(32);

                    }));
      }));
```

if I manually change it to:
```
Vitest$1.describe("T1", (function (param) {
        return Vitest$1.it("T11", (function (_t) {
                      Vitest$1.expect(1).toEqual(32);

                    }));
      }));
```

then it works.

**Comment by thomaszdxsn** [comment]
same issue

**Comment by cometkim** [comment]
Please provide a reproducible ReScript source code as well.

**Comment by thomaszdxsn** [comment]
the reason is vitest#0.2.7, when i turn my version to `"^0.1.13"`, it's worked

**Comment by cometkim** [comment]
I see.

~~Hmm, I think I should provide `vitest` as dependency instead of using peer's one~~

Already did, It is not intended to use with hoisted peer dependencies.

I will update it to 0.2.x soon.

**Comment by cometkim** [comment]
@giraud @thomaszdxsn 

I just released a new version. Can you try again with v0.2.0?

This is expected result:
![image](https://user-images.githubusercontent.com/9696352/153271280-06ef9df7-c110-4d56-910d-9440e8f41977.png)

**Comment by thomaszdxsn** [comment]
Sorry, I just try vitest but found can't swith my project to `es6`. So I turn test framework to `rescript-jest`.

Maybe use vitest on next project

**Comment by giraud** [comment]
@cometkim  thank you for the update.
unfortunately, it's the same. something might be wrong with my config.
I'm closing that bug because I don't have time to go deeper.
